Removed debugging statements Handle stat correctly
git-svn-id: http://casacore.googlecode.com/svn/trunk@20748 6afa274c-0927-0410-9b47-a1284d797885

diff --git a/casa/tools/casacore_assay b/casa/tools/casacore_assay
--- a/casa/tools/casacore_assay
+++ b/casa/tools/casacore_assay
@@ -177,17 +177,18 @@ EOF
      exit
   fi
   # Not fully equal. Check with floating point accuracy.
-  stat=floatcheck ${1}_tmp.out ${1}_tmpo.out 1e-5
+  floatcheck ${1}_tmp.out ${1}_tmpo.out 1e-5
+  stat=$?
   case $stat in
   0)
      echo "PASS (floating point discrepancies <= 1e-5): $1"
      ;;
   1)
-     echo "FAIL (output not verified): $*"
+     echo "FAIL (output not verifie): $*"
      ;;
   *)
      echo "FAIL (floating point discrepancies > 1e-5): $1"
      ;;
   esac
-  STATUS=stat
+  STATUS=$stat
   exit
